[package]
name = "eth_transaction_handler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.13"
ic-cdk-macros = "0.9"
serde = { version = "1.0", features = ["derive"] }
hex = "0.4"
sha3 = "0.10"
rlp = "0.5"
k256 = { version = "0.11", default-features = false, features = ["ecdsa", "ecdsa-core", "sha256"] }

[profile.release]
lto = true
opt-level = 'z'