#!/bin/bash

# Fix Ethereum deposit issues by setting the correct contract address

echo "🔧 Fixing Ethereum deposit configuration..."

# Latest deployed contract address from deployments/sepolia.json
CONTRACT_ADDRESS="0x8626502727D7faf282C44df18B34E50D0DB45Eae"

# Ethereum Adapter canister ID (mainnet)
ETHEREUM_ADAPTER="icmw4-miaaa-aaaad-qhmmq-cai"

echo "📋 Contract Address: $CONTRACT_ADDRESS"
echo "🔗 Ethereum Adapter: $ETHEREUM_ADAPTER"

# Set the deposit contract address
echo ""
echo "Setting deposit contract address on EthereumAdapter..."
dfx canister call $ETHEREUM_ADAPTER setDepositContract "(\"$CONTRACT_ADDRESS\")" --ic

echo ""
echo "✅ Configuration updated!"
echo ""
echo "📝 IMPORTANT: The current deposit flow has issues:"
echo "   1. Users send ETH to unique addresses generated by the canister"
echo "   2. The canister needs to forward these funds to the pool contract"
echo "   3. This forwarding mechanism is NOT implemented yet"
echo ""
echo "🚨 For now, users should deposit directly to the contract at:"
echo "   $CONTRACT_ADDRESS"
echo ""
echo "💡 To test deposits:"
echo "   1. Use scripts/test_deposit.js (deposits directly to contract)"
echo "   2. Monitor with: dfx canister call $ETHEREUM_ADAPTER checkDeposits --ic"