#!/bin/bash

# Test deposit to Sepolia address
DEPOSIT_ADDRESS="0x997ec52a49f3c52a0b375cfbccb988aadaedd0e8"
AMOUNT="0.1"
NETWORK="sepolia"

echo "🚀 Testing Ethereum Deposit on Sepolia"
echo "=================================="
echo "📍 Deposit Address: $DEPOSIT_ADDRESS"
echo "💰 Amount: $AMOUNT ETH"
echo "🌐 Network: Sepolia Testnet"
echo ""
echo "To make the deposit:"
echo ""
echo "1. Get Sepolia ETH from faucets:"
echo "   - https://sepoliafaucet.com/"
echo "   - https://sepolia-faucet.pk910.de/"
echo "   - https://faucet.quicknode.com/ethereum/sepolia"
echo ""
echo "2. Using MetaMask or any wallet:"
echo "   a) Switch to Sepolia network"
echo "   b) Send exactly $AMOUNT ETH to:"
echo "   $DEPOSIT_ADDRESS"
echo ""
echo "3. After sending, click 'I've Made the Deposit' in the app"
echo ""
echo "The system will:"
echo "- Monitor the address for incoming funds"
echo "- Forward the funds to the deposit contract"
echo "- Register your deposit with the commitment"
echo "- Provide you with a private note for withdrawal"